version: '3.8'

services:
  kabisa-new-backend:
    container_name: kabisa-new-backend
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/programmerdatch/kabisa-new-backend:latest
    ports:
      - "7018:${PORT:-9090}"
    env_file:
      - .env
    environment:
      - LOGS_DIR=/app/logs
    command: npm start
    restart: always
    volumes:
      - ./logs:/app/logs
    networks:
      - kabisa-new-network

networks:
  kabisa-new-network:
    driver: bridge
