services:
  - type: web
    name: nft-marketplace-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 9090
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: GOOGLE_CLIENT_ID
        sync: false
        optional: true
      - key: GOOGLE_CLIENT_SECRET
        sync: false
        optional: true


